"""Cryptographic SHA-256 Hash-Chained Audit Logger for Tamper-Evident SIEM Trails."""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


class AuditLogger:
    """Appends audit events into a tamper-evident, cryptographic SHA-256 hash chain."""

    GENESIS_HASH = "0000000000000000000000000000000000000000000000000000000000000000_GENESIS"

    def __init__(self, log_path: str = "logs/audit.log") -> None:
        """
        Initialize audit logger and ensure parent directories exist.
        
        Args:
            log_path: Path to the JSONL audit log file.
        """
        self.log_path = Path(log_path)
        self.log_path.parent.mkdir(parents=True, exist_ok=True)

    def get_latest_hash(self) -> str:
        """
        Retrieve the cryptographic hash of the most recent audit entry.
        
        Returns:
            SHA-256 hex string of the last entry, or GENESIS_HASH if log is empty.
        """
        if not self.log_path.exists() or self.log_path.stat().st_size == 0:
            return self.GENESIS_HASH

        with self.log_path.open("rb") as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]
            if not lines:
                return self.GENESIS_HASH
            try:
                last_record = json.loads(lines[-1].decode("utf-8"))
                return last_record.get("hash", self.GENESIS_HASH)
            except (json.JSONDecodeError, UnicodeDecodeError):
                return self.GENESIS_HASH

    def log_event(
        self,
        username: str,
        role: str,
        document_id: str,
        prompt: str,
        outcome: str,
        reason: str,
        response: Optional[str] = None,
        redactions_applied: bool = False,
        extra_metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Create, hash-chain, and persist an audit event record.
        
        Args:
            username: Identifier of the requesting user.
            role: Assigned role of the user.
            document_id: Target document identifier.
            prompt: Sanitized/redacted prompt submitted.
            outcome: "allowed" or "blocked".
            reason: Specific reason (e.g. "ok", "rbac_denied", "prompt_injection").
            response: Redacted response generated by model (if allowed).
            redactions_applied: True if DLP masking altered the prompt or response.
            extra_metadata: Optional additional metadata dict.
            
        Returns:
            The complete persisted event dict including hashes.
        """
        previous_hash = self.get_latest_hash()
        timestamp = datetime.now(timezone.utc).isoformat()

        payload: Dict[str, Any] = {
            "timestamp": timestamp,
            "user": username,
            "role": role,
            "document_id": document_id,
            "prompt": prompt,
            "outcome": outcome,
            "reason": reason,
            "response": response,
            "redactions_applied": redactions_applied,
            "previous_hash": previous_hash,
        }

        if extra_metadata:
            payload["metadata"] = extra_metadata

        # Compute deterministic SHA-256 hash over canonical JSON representation
        canonical_str = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        calculated_hash = hashlib.sha256(canonical_str.encode("utf-8")).hexdigest()
        payload["hash"] = calculated_hash

        # Append to log file
        with self.log_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(payload, sort_keys=True) + "\n")

        return payload

    @classmethod
    def verify_integrity(cls, log_path: str) -> Tuple[bool, int, str]:
        """
        Verify the mathematical integrity of an audit log file.
        
        Args:
            log_path: Path to the JSONL log file to inspect.
            
        Returns:
            Tuple of (is_valid: bool, records_verified: int, message: str)
        """
        path = Path(log_path)
        if not path.exists() or path.stat().st_size == 0:
            return True, 0, f"Log file is empty or not yet generated at {log_path} (0 records)."

        with path.open("r", encoding="utf-8") as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]

        if not lines:
            return True, 0, "Log file is empty (0 records)."

        expected_previous_hash = cls.GENESIS_HASH

        for index, line in enumerate(lines):
            try:
                record = json.loads(line)
            except json.JSONDecodeError as e:
                return False, index, f"Corrupted JSON syntax at record #{index + 1}: {str(e)}"

            recorded_hash = record.get("hash")
            recorded_previous_hash = record.get("previous_hash")

            # 1. Verify previous hash link
            if recorded_previous_hash != expected_previous_hash:
                return (
                    False,
                    index,
                    f"Hash chain broken at record #{index + 1}. Expected previous_hash '{expected_previous_hash}', found '{recorded_previous_hash}'."
                )

            # 2. Recompute record hash
            payload_copy = record.copy()
            payload_copy.pop("hash", None)
            canonical_str = json.dumps(payload_copy, sort_keys=True, separators=(",", ":"))
            computed_hash = hashlib.sha256(canonical_str.encode("utf-8")).hexdigest()

            if computed_hash != recorded_hash:
                return (
                    False,
                    index,
                    f"Tampered record at line #{index + 1}! Computed hash '{computed_hash}' does not match recorded hash '{recorded_hash}'."
                )

            expected_previous_hash = recorded_hash

        return True, len(lines), f"Cryptographic audit log verified successfully. {len(lines)} records intact."
