"""Prompt Injection Guardrails, Canary Token Tripwires, and Output Sanitization."""

import re
import secrets
import string
from typing import List, Optional, Tuple


class PromptInjectionDetector:
    """Detects prompt injection and jailbreak attacks (OWASP LLM01)."""

    INJECTION_RULES = (
        r"ignore\s+(?:all\s+)?(?:previous|prior|above)\s+(?:instructions|prompts|rules|commands)",
        r"bypass\s+(?:security|guardrails|safety|filters|protections|restrictions)",
        r"reveal\s+(?:system\s+prompt|hidden\s+instructions|internal\s+instructions|master\s+prompt)",
        r"(?:act|operate|behave)\s+as\s+(?:developer|dan|jailbroken|unrestricted|godmode|admin)",
        r"disable\s+(?:all\s+)?(?:guardrails|safety|filters|rules|restrictions)",
        r"you\s+are\s+now\s+in\s+(?:dan|developer|jailbreak|debug)\s+mode",
        r"do\s+anything\s+now",
        r"disregard\s+(?:any\s+)?(?:rules|instructions|safety|guidelines)",
        r"</(?:context|instruction|system|prompt)>",
        r"\[/?(?:system|developer|instruction)\]",
        r"<\|(?:im_start|im_end|system|user|assistant)\|>",
    )

    def __init__(self, custom_rules: Optional[List[str]] = None) -> None:
        """
        Initialize detector with compiled regex patterns.
        
        Args:
            custom_rules: Optional list of additional regex pattern strings.
        """
        rules = list(self.INJECTION_RULES)
        if custom_rules:
            rules.extend(custom_rules)
        self.compiled_rules = [re.compile(pattern, re.IGNORECASE) for pattern in rules]

    def is_injection(self, prompt: str) -> bool:
        """
        Scan a prompt for known injection or jailbreak patterns.
        
        Args:
            prompt: User input prompt string.
            
        Returns:
            True if injection pattern detected, False if clean.
        """
        if not prompt:
            return False
        normalized = " ".join(prompt.lower().split())
        return any(rule.search(normalized) for rule in self.compiled_rules)

    def get_matched_rules(self, prompt: str) -> List[str]:
        """
        Return the list of pattern strings that matched the prompt.
        
        Args:
            prompt: User input prompt string.
            
        Returns:
            List of matching regex pattern strings.
        """
        if not prompt:
            return []
        normalized = " ".join(prompt.lower().split())
        matches = []
        for rule in self.compiled_rules:
            if rule.search(normalized):
                matches.append(rule.pattern)
        return matches


class CanaryTokenManager:
    """Generates and tracks ephemeral canary tokens to detect context extraction."""

    def __init__(self, token_length: int = 16) -> None:
        self.token_length = token_length

    def generate_token(self) -> str:
        """Generate a cryptographically secure random canary token."""
        alphabet = string.ascii_uppercase + string.digits
        random_suffix = "".join(secrets.choice(alphabet) for _ in range(self.token_length))
        return f"CANARY_VAULT_{random_suffix}"

    def is_canary_leaked(self, response_text: str, canary_token: str) -> bool:
        """
        Check if the model's generated response contains the canary token.
        
        Args:
            response_text: Text generated by the LLM.
            canary_token: The secret canary token injected into system prompt.
            
        Returns:
            True if canary is present in output (indicating system prompt leak).
        """
        if not response_text or not canary_token:
            return False
        return canary_token in response_text


class OutputSanitizer:
    """Sanitizes model outputs to prevent insecure output handling (OWASP LLM02)."""

    SCRIPT_PATTERN = re.compile(r"<\s*script[^>]*>.*?<\s*/\s*script\s*>", re.IGNORECASE | re.DOTALL)
    HTML_TAG_PATTERN = re.compile(r"<\s*(iframe|embed|object|meta|link)[^>]*>", re.IGNORECASE)
    JAVASCRIPT_URI_PATTERN = re.compile(r"javascript:\s*[^\"\'\s>]+", re.IGNORECASE)

    def sanitize(self, text: str) -> str:
        """
        Strip raw executable scripts, embedded frames, and dangerous javascript URIs.
        
        Args:
            text: Raw model output.
            
        Returns:
            Sanitized safe output string.
        """
        if not text:
            return ""
        cleaned = self.SCRIPT_PATTERN.sub("[UNSAFE_SCRIPT_REMOVED]", text)
        cleaned = self.HTML_TAG_PATTERN.sub("[UNSAFE_HTML_TAG_REMOVED]", cleaned)
        cleaned = self.JAVASCRIPT_URI_PATTERN.sub("#", cleaned)
        return cleaned
